'欢迎语': '欢迎您加入国内首家线上健身社交平台。
          美型拥有庞大的运动健身场地，并且展示驻地私教，您可用根据自己到运动健身需求选择对应的运动健身课程。
          分享与运动圈动态，来“约”更多型男美女，让运动健身不再孤单。
         【美型】2.0全线上线，运动健身哪家强，卖课“约”课美型强'
'消课': '您的%s课程,已消一课时,课单号%s,上课后别忘记秀成果哦'
'订单': '学员%s购买了您的%s课程，订单编号%s，赶紧登陆去查看订单，别忘记联系学员哦！'